version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
      - /var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop

  prestashop:
    container_name: prestashop
    depends_on:
      - mysql
    build:
      context: ./ssl
    ports:
      - 8000:80
      - 8001:443
    restart: always
    environment:
      DB_SERVER: mysql
      DB_USER: root
      DB_PASSWD: root
      DB_NAME: prestashop
      PS_FOLDER_ADMIN: admin
      PS_FOLDER_INSTALL: install
      PS_INSTALL_AUTO: 0
    networks:
      - prestashop
networks:
  prestashop:
