version: '3'

services:
  be_teamX:
    image: michal299/be_175132
    ports:
      - 15132:80
      - 15133:443
    restart: always
    environment:
      DB_SERVER: actina15.maas
      DB_USER: BE_175132_user
      DB_PASSWD: password
      DB_NAME: BE_175132_db
      PS_FOLDER_ADMIN: admin
      PS_FOLDER_INSTALL: install
      PS_INSTALL_AUTO: 0
    deploy:
      replicas: 1