<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYi2szhe\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYi2szhe/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYi2szhe.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYi2szhe\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYi2szhe\appProdProjectContainer([
    'container.build_hash' => 'Yi2szhe',
    'container.build_id' => '6f9ba375',
    'container.build_time' => 1637400831,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYi2szhe');
