<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4qzba9q\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4qzba9q/appProdProjectContainer.php') {
    touch(__DIR__.'/Container4qzba9q.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container4qzba9q\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container4qzba9q\appProdProjectContainer([
    'container.build_hash' => '4qzba9q',
    'container.build_id' => 'b8eec302',
    'container.build_time' => 1637400874,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4qzba9q');
